engines: 
  eslint:
    enabled: true 
  duplication:
  	enabled: true
    config:
    	languages: 
      - javascript
eslint:
  enabled: true 
  config:
    extensions:
    - .es6
    - .js
    - .jsx      
ratings:
  paths:
  - src/** 
exclude_paths:
- node_modules